audit:
  disableCertRotation: true
  podLabels:
    tags.datadoghq.com/service: gatekeeper-audit

controllerManager:
  disableCertRotation: true
  podLabels:
    tags.datadoghq.com/service: gatekeeper-controller-manager

externalCertInjection:
  enabled: true

podLabels:
  tags.datadoghq.com/service: gatekeeper

mutatingWebhookAnnotations:
  cert-manager.io/inject-ca-from: gatekeeper-system/gatekeeper-webhook-server-cert

validatingWebhookAnnotations:
  cert-manager.io/inject-ca-from: gatekeeper-system/gatekeeper-webhook-server-cert
